version: '3.7'

services:
  wallet-api:
    container_name: wallet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: wallet
